version: 1.0.{build}

image:
  - Visual Studio 2017

environment:
  DOCKER_USER: "mvallim"
  DOCKER_PASS:
    secure: C2jl7oXoaoVnUHnhrHMKug==
  IMAGE: "jnlp-slave-dotnet-framework"

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

skip_commits:
  files:
    - docs/*
    - '**/*.md'  
    
install:
  - docker version

build_script:
  - docker build --rm -t %DOCKER_USER%/%IMAGE%:latest .
  - docker tag %DOCKER_USER%/%IMAGE%:latest %DOCKER_USER%/%IMAGE%:%APPVEYOR_BUILD_VERSION%

deploy:
  - provider: Environment
    on:
      branch: /^v\d+\.\d+(\.\d+)?(-\S*)?$/
      appveyor_repo_tag: true
      
deploy_script:
  - docker login -u="%DOCKER_USER%" -p="%DOCKER_PASS%"
  - docker push %DOCKER_USER%/%IMAGE%:latest
  - docker push %DOCKER_USER%/%IMAGE%:%APPVEYOR_BUILD_VERSION%
