version: 1.0.44

image:
  - Visual Studio 2017

environment:
  DOCKER_USER: "mvallim"
  DOCKER_PASS:
    secure: C2jl7oXoaoVnUHnhrHMKug==
  IMAGE: "jnlp-slave-dotnet-framework"

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

skip_commits:
  files:
    - docs/*
    - '**/*.md'  
    
install:
  - docker version

build_script:
  - echo "build"
#  - docker build --rm -t %DOCKER_USER%/%IMAGE%:latest .
#  - docker tag %DOCKER_USER%/%IMAGE%:latest %DOCKER_USER%/%IMAGE%:%APPVEYOR_BUILD_VERSION%

deploy_script:
  - ps: | 
          $ErrorActionPreference = "Stop"
          #if ($env:APPVEYOR_REPO_TAG -eq "true") { 
            docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
            #docker push $env:DOCKER_USER/$env:IMAGE:latest
            #docker push $env:DOCKER_USER/$env:IMAGE:$env:APPVEYOR_BUILD_VERSION 
          #}
          echo "Done"
