version: 1.0.{build}

image:
  - Visual Studio 2017

environment:
  DOCKER_USER: "mvallim"
  DOCKER_PASS:
    secure: C2jl7oXoaoVnUHnhrHMKug==
  IMAGE: "jnlp-slave-dotnet-framework"
  VERSION: "1.0.0"

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

skip_commits:
  files:
    - docs/*
    - '**/*.md'  
    
install:
  - docker version

build_script:
  - echo "build"
#  - docker build --rm -t %DOCKER_USER%/%IMAGE%:latest .
#  - docker tag %DOCKER_USER%/%IMAGE%:latest %DOCKER_USER%/%IMAGE%:%VERSION%

deploy_script:
  - ps: |
      #if ($env:APPVEYOR_REPO_TAG EQU "true") { 
        docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS" | out-null
        #docker push $env:DOCKER_USER/$env:IMAGE:latest
        #docker push $env:DOCKER_USER/$env:IMAGE:$env:VERSION 
      #}
      echo "Done"
