version: 1.0.{build}
image:
  - Visual Studio 2017

environment:
  DOCKER_USER: "mvallim"
  DOCKER_PASS:
    secure: C2jl7oXoaoVnUHnhrHMKug==
  IMAGE: "jnlp-slave-dotnet-framework"
    
install:
  - docker version

build_script:
  - docker build --rm -t %DOCKER_USER%/%IMAGE%:latest ./docker/Dockerfile
  - docker tag %DOCKER_USER%/%IMAGE%:latest %DOCKER_USER%/%IMAGE%:{version}

test_script:
  - docker run %DOCKER_USER%/%IMAGE%:latest
  - docker run %DOCKER_USER%/%IMAGE%:{version}

deploy_script:
  - docker login -u="%DOCKER_USER%" -p="%DOCKER_PASS%"
  - docker push %DOCKER_USER%/%IMAGE%:latest
  - docker push %DOCKER_USER%/%IMAGE%:{version}
