version: 1.0.{build}

image:
  - Visual Studio 2017

environment:
  DOCKER_USER: "mvallim"
  DOCKER_PASS:
    secure: C2jl7oXoaoVnUHnhrHMKug==
  IMAGE: "jnlp-slave-dotnet-framework"
  VERSION: "1.0.0"

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

skip_commits:
  files:
    - docs/*
    - '**/*.md'  
    
install:
  - docker version

build_script:
  - echo %DOCKER_USER%/%IMAGE%:latest
#  - docker build --rm -t %DOCKER_USER%/%IMAGE%:latest .
#  - docker tag %DOCKER_USER%/%IMAGE%:latest %DOCKER_USER%/%IMAGE%:%VERSION%

after_build:
  - docker images  

deploy_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "false") { 
        echo $env:DOCKER_PASS | docker login -u="$env:DOCKER_USER" --password-stdin
        echo ($env:DOCKER_USER)/($env:IMAGE)
        echo ($env:DOCKER_USER)/($env:IMAGE):latest
        echo ($env:DOCKER_USER)/($env:IMAGE):($env:VERSION)
      }
      echo "Done"
